import type { PieceType } from "./khmer-chess";

export type Lesson = {
  id: string;
  piece: PieceType;
  title: Record<string, string>;
  goal: Record<string, string>;
  details: Record<string, string>;
};

export const LESSONS: Lesson[] = [
  {
    id: "l1",
    piece: "p",
    title: {
      en: "Trey Advance & Promotion",
      vi: "Tiến quân Trey & Phong cấp",
      km: "ការរុលត្រី និងការបក",
      fr: "Avancée du Trey & Promotion",
      th: "การเดินเบี้ยตรีและการหงาย",
      zh: "兵 (Trey) 的推进行与升变",
    },
    goal: {
      en: "Push connected fish to the 6th rank where they promote into Trey Bork (Neang).",
      vi: "Tiến đàn tốt liên kết lên hàng 6 để lật thành Trey Bork (tương đương Hậu Neang).",
      km: "រុលកូនត្រីឡើងដល់ជួរទី ៦ ដើម្បីបកទៅជាត្រីបក (ស្មើនឹងនាង)។",
      fr: "Poussez les poissons liés jusqu'à la 6e rangée pour les promouvoir en Trey Bork.",
      th: "เดินเบี้ยผูกขึ้นสู่แถวที่ 6 เพื่อหงายเป็นเบี้ยหงาย (เม็ด)",
      zh: "推进相连的兵至第6横线，将其升变为后 (Trey Bork)。",
    },
    details: {
      en: "Trey moves 1 step forward and captures 1 step diagonally forward. At the 6th rank (opposing pawn line), it flips over into Trey Bork.",
      vi: "Tốt Trey đi thẳng 1 ô và ăn chéo 1 ô về phía trước. Khi đến hàng 6 (hàng Tốt ban đầu của đối phương), Trey được lật thành Trey Bork (ăn và đi chéo 1 ô mọi hướng).",
      km: "ត្រីដើរត្រង់ ១ ក្រឡា និងស៊ីបញ្ឆិតមុខ ១ ក្រឡា។ ដល់ជួរទី ៦ ត្រូវបកជាត្រីបក (ដើរ និងស៊ីបញ្ឆិត ១ ក្រឡាគ្រប់ទិស)។",
      fr: "Le Trey avance d'une case tout droit et capture en diagonale vers l'avant. À la 6e rangée, il devient Trey Bork.",
      th: "เบี้ยเดินตรง 1 ช่อง และกินทแยงหน้า 1 ช่อง เมื่อถึงแถวที่ 6 จะหงายเป็นเบี้ยหงาย (เดิน/กินทแยง 4 ทิศทางละ 1 ช่อง)",
      zh: "兵向前走一直格，向前斜走一格吃子。到达第6横线时升变为“升变兵”（走法等同于后）。",
    },
  },
  {
    id: "l2",
    piece: "q",
    title: {
      en: "Neang Agility & Opening Leap",
      vi: "Sự cơ động của Hậu Neang",
      km: "ភាពបត់បែនរបស់នាង",
      fr: "Agilité de la Reine Neang",
      th: "ความคล่องตัวของเม็ดเนียง",
      zh: "后 (Neang) 的机动与首步跳跃",
    },
    goal: {
      en: "Neang moves 1 step diagonally in all 4 directions. In folk rules, its first move can jump 2 squares forward.",
      vi: "Neang đi 1 ô chéo theo 4 hướng. Trong luật dân gian, nước đầu tiên của Neang có thể nhảy 2 ô thẳng về phía trước.",
      km: "នាងដើរបញ្ឆិត ១ ក្រឡាទាំង ៤ ទិស។ ក្នុងច្បាប់បុរាណ ដើរដំបូងអាចលោតត្រង់ ២ ក្រឡា។",
      fr: "La Neang se déplace d'une case en diagonale (4 directions). En règles traditionnelles, son premier coup peut sauter 2 cases en avant.",
      th: "เม็ดเดินทแยง 4 ทิศทางละ 1 ช่อง ในกติกาพื้นบ้าน ตาแรกสามารถกระโดดตรงไปข้างหน้าได้ 2 ช่อง",
      zh: "后可向4个斜向各走1格。在民间规则中，其第一步可行使特权向前跳跃2格。",
    },
    details: {
      en: "In International SEA Games rules, the opening leap is omitted. Neang always moves 1 diagonal step.",
      vi: "Trong luật thi đấu quốc tế SEA Games, đặc quyền nhảy khai cuộc bị bãi bỏ. Neang luôn di chuyển 1 ô chéo.",
      km: "ក្នុងច្បាប់អន្តរជាតិស៊ីហ្គេម គ្មានការលោតបើកឆាកឡើយ នាងដើរត្រឹម ១ ក្រឡាបញ្ឆិត។",
      fr: "Aux Jeux d'Asie du Sud-Est, le saut initial est aboli. La Neang avance toujours d'une case en diagonale.",
      th: "ในกติกาสากลซีเกมส์ ไม่มีตากระโดดเปิดเกม เม็ดเดินทแยง 1 ช่องเสมอ",
      zh: "在东南亚运动会国际竞赛规则中，后取消首步跳跃特权，始终按单格斜向移动。",
    },
  },
  {
    id: "l3",
    piece: "b",
    title: {
      en: "Koul (Elephant) Five-Direction Shield",
      vi: "Lá chắn 5 hướng của Tượng Koul",
      km: "ខែល ៥ ទិសរបស់គោល (ដំរី)",
      fr: "Le bouclier à 5 directions du Koul",
      th: "โล่ 5 ทิศของโคนคูล",
      zh: "相 (Koul) 的五向铁壁",
    },
    goal: {
      en: "Koul moves 1 square diagonally (4 directions) OR 1 square straight forward (5 directions total).",
      vi: "Koul đi 1 ô chéo (4 hướng) HOẶC 1 ô thẳng về phía trước (tổng cộng 5 hướng). Koul không thể lùi thẳng.",
      km: "គោលដើរបាន ៥ ទិស (បញ្ឆិត ៤ ទិស ឬ ត្រង់ទៅមុខ ១ ក្រឡា)។ មិនអាចថយក្រោយត្រង់បានឡើយ។",
      fr: "Le Koul se déplace d'une case en diagonale (4 directions) OU d'une case droit devant (5 directions au total).",
      th: "โคนเดินได้ 5 ทิศทาง (ทแยง 4 ทิศ หรือ ตรงไปข้างหน้า 1 ช่อง) ไม่สามารถถอยตรงได้",
      zh: "相可向4个斜向各走1格，或向前直走1格（共5个方向）。不能直接向后退。",
    },
    details: {
      en: "Koul excels at supporting central pawn thrusts and anchoring the royal guard fortress around the King.",
      vi: "Koul phối hợp hoàn hảo với Tốt để chiếm lĩnh trung tâm và tạo thành lá chắn kiên cố bảo vệ Vua.",
      km: "គោលស័ក្តិសមបំផុតក្នុងការការពារកណ្តាលក្តារ និងការពារអង្គ (ស្តេច)។",
      fr: "Le Koul excelle dans le soutien des pions centraux et la garde royale.",
      th: "โคนมีประสิทธิภาพสูงในการคุมศูนย์กลางและตั้งรับรอบขุน",
      zh: "相与兵协同作战极为严密，是护卫王宫和巩固阵地前沿的核心重装部队。",
    },
  },
  {
    id: "l4",
    piece: "n",
    title: {
      en: "Ses (Horse) Cavalry Tactics",
      vi: "Chiến thuật Kỵ binh Mã Ses",
      km: "យុទ្ធសាស្ត្រទ័ពសេះ",
      fr: "Tactiques de cavalerie du Ses",
      th: "ยุทธวิธีม้าเซส",
      zh: "马 (Ses) 的八面穿插突袭",
    },
    goal: {
      en: "Ses moves in an 'L' shape (2 squares in one direction, 1 square perpendicular) and jumps over all intervening pieces.",
      vi: "Mã Ses đi hình chữ L (2 ô một chiều, 1 ô vuông góc) và nhảy tự do qua các quân cản đường.",
      km: "សេះដើររាងអក្សរ L និងអាចលោតរំលងកូនអុកផ្សេងទៀតបានដោយគ្មានឧបសគ្គ។",
      fr: "Le Ses se déplace en 'L' et saute par-dessus les autres pièces sans blocage.",
      th: "ม้าเดินเป็นรูปตัว L และสามารถกระโดดข้ามหมากตัวอื่นได้เสมอ",
      zh: "马走“日”字形（先直一格再斜一格），且没有中国象棋中的“蹩马腿”规则，可自由跃过障碍。",
    },
    details: {
      en: "Ses is identical to Western chess knight. It controls 8 squares from the center.",
      vi: "Mã Ses có nước đi tương tự như Mã cờ vua quốc tế, khống chế tối đa 8 ô khi đứng ở trung tâm.",
      km: "សេះមានចលនាដូចសេះអុកសកល មានអំណាចគ្រប់គ្រង ៨ ក្រឡានៅចំកណ្តាលក្តារ។",
      fr: "Identique au cavalier des échecs occidentaux, le Ses contrôle jusqu'à 8 cases.",
      th: "ม้ามีลักษณะการเดินเหมือนม้าหมากรุกสากล คุมพื้นที่ได้สูงสุด 8 ช่องรอบตัว",
      zh: "马在中腹可同时控驭8个落点，具有极强的穿透力与战术奇袭效果。",
    },
  },
  {
    id: "l5",
    piece: "r",
    title: {
      en: "Tuuk (Boat) Open File Domination",
      vi: "Thuyền Tuuk làm chủ cột mở",
      km: "ទូកគ្រប់គ្រងជួរកណ្តាល",
      fr: "Le Bateau Tuuk sur les colonnes ouvertes",
      th: "เรือทูคคุมแนวเปิด",
      zh: "车/船 (Tuuk) 纵横全图霸权",
    },
    goal: {
      en: "Tuuk moves orthogonally any number of unoccupied squares in all 4 directions.",
      vi: "Thuyền Tuuk đi thẳng theo chiều ngang hoặc dọc bất kỳ số ô nào miễn là đường đi thông suốt.",
      km: "ទូកដើរត្រង់តាមបណ្តោយ និងទទឹងបានគ្រប់ចំនួនក្រឡាដែលគ្មានឧបសគ្គ។",
      fr: "Le Tuuk se déplace orthogonalement sur toute case libre dans les 4 directions.",
      th: "เรือเดินหน้า ถอยหลัง หรือไปด้านข้างได้ไม่จำกัดช่องตราบใดที่ไม่มีหมากขวาง",
      zh: "车可在横竖四个直线上无限格行驶，是整个高棉战阵中远程威慑力最强的王牌重子。",
    },
    details: {
      en: "Tuuk is the most powerful piece in Ouk Chatrang (worth 8 points). Losing a Tuuk creates immense counting disadvantage.",
      vi: "Tuuk là quân cờ mạnh nhất trong cờ Ốc (giá trị 8 điểm). Trong tàn cuộc, 2 Xe chỉ mất 8 nước đếm, 1 Xe mất 16 nước đếm.",
      km: "ទូកជាកូនអុកខ្លាំងបំផុត (តម្លៃ ៨ ពិន្ទុ) ដើរតួនាទីសំខាន់ក្នុងការរាប់វាល។",
      fr: "Le Tuuk est la pièce la plus puissante du jeu (valeur 8).",
      th: "เรือเป็นหมากที่ทรงพลังที่สุด (มูลค่า 8 แต้ม) มีบทบาทสำคัญในการนับศักดิ์ปลายกระดาน",
      zh: "车是全盘威力最强大的兵种（价值8分）。残局时双车杀单王仅需8步数步上限，单车为16步。",
    },
  },
  {
    id: "l6",
    piece: "k",
    title: {
      en: "Ang (King) Protection & Folk Leap",
      vi: "Bảo vệ Vua Ang & Đặc quyền Vua",
      km: "ការការពារអង្គ និងការលោតបើកឆាក",
      fr: "Protection du Roi Ang & Saut royal",
      th: "การรักษาขุนอังและตากระโดดเปิดเกม",
      zh: "王 (Ang) 的统御与民间跃步",
    },
    goal: {
      en: "Ang moves 1 step in any direction (8 squares). In folk rules, its first move can leap like a knight if unattacked.",
      vi: "Vua Ang đi 1 ô theo mọi hướng (8 ô xung quanh). Trong luật dân gian, nước đi đầu tiên của Vua có thể nhảy như Mã nếu chưa bị chiếu.",
      km: "អង្គដើរបាន ១ ក្រឡាគ្រប់ទិស (៨ ក្រឡា)។ ក្នុងច្បាប់បុរាណ ដើរដំបូងអាចលោតដូចសេះបាន។",
      fr: "L'Ang se déplace d'une case dans toutes les directions (8 cases). En règles traditionnelles, son premier coup peut sauter comme un cavalier.",
      th: "ขุนเดินได้ 8 ทิศทางละ 1 ช่อง ในกติกาพื้นบ้าน ตาแรกสามารถกระโดดแบบม้าได้หากยังไม่ถูกรุก",
      zh: "王可向全方位8个相邻格各走1格。民间规则中，未受攻击的首步可如马般跃步入阵。",
    },
    details: {
      en: "In International SEA Games rules, the King's opening leap is strictly forbidden. The game ends in Ouk Ngueb (Checkmate).",
      vi: "Trong luật quốc tế SEA Games, Vua không được nhảy khai cuộc. Trò chơi kết thúc khi Vua bị chiếu hết (Ouk Ngueb) hoặc hòa đếm Viel.",
      km: "ក្នុងច្បាប់អន្តរជាតិស៊ីហ្គេម ការលោតរបស់អង្គត្រូវបានហាមឃាត់ដាច់ខាត។",
      fr: "Aux Jeux d'Asie du Sud-Est, le saut du roi est interdit. La partie se termine par Ouk Ngueb.",
      th: "ในการแข่งขันระดับสากลซีเกมส์ ไม่อนุญาตให้ขุนกระโดดตาแรก จบเกมด้วยการรุกจน (Ouk Ngueb)",
      zh: "东南亚运动会竞技规则严禁王首步跃步。全盘胜负依杀局 (Ouk Ngueb)、认输、超时或和棋数步而定。",
    },
  },
];

export const HANDBOOK_I18N: Record<string, Record<string, string>> = {
  angkor_badge: {
    en: "Angkor 802 AD · 10 Sections",
    vi: "Angkor 802 SCN · 10 Phần",
    km: "អង្គរ គ.ស. ៨០២ · ១០ ជំពូក",
    fr: "Angkor 802 ap. J.-C. · 10 Sections",
    th: "นครวัด ค.ศ. 802 · 10 หมวดหมู่",
    zh: "公元802年吴哥王朝 · 全书10章",
  },
  // Section 1
  sec1_text: {
    en: "Ouk Chatrang is a thousand-year-old royal intellectual heritage of the Angkor Empire, vividly depicted on the stone bas-reliefs of Angkor Wat and Bayon temples since the 12th century. The name 'Ouk' originates from the loud call made when checking the King.",
    vi: "Cờ Ốc (Ouk Chatrang) là di sản trí tuệ ngàn năm của nền văn minh Angkor rực rỡ, được khắc họa tinh xảo trên các bức phù điêu sa thạch tại đền Angkor Wat và đền Bayon từ thế kỷ 12. Tên gọi 'Ouk' bắt nguồn từ tiếng hô vang hào hùng khi thực hiện nước chiếu Vua.",
    km: "អុកចត្រង្គ គឺជាកេរដំណែលបញ្ញាវន្តរាប់ពាន់ឆ្នាំនៃអរិយធម៌អង្គរដ៏រុងរឿង ដែលត្រូវបានចាក់ឆ្លាក់យ៉ាងរស់រវើកនៅលើជញ្ជាំងថ្មប្រាសាទអង្គរវត្ត និងប្រាសាទបាយ័នតាំងពីសតវត្សរ៍ទី ១២។ ពាក្យថា «អុក» កើតចេញពីសំឡេងបន្លឺឡើងនៅពេលអុកស្តេចគូប្រកួត។",
    fr: "L'Ouk Chatrang est un héritage intellectuel millénaire de la civilisation d'Angkor, sculpté sur les bas-reliefs des temples d'Angkor Wat et du Bayon dès le XIIe siècle. Le nom 'Ouk' provient du cri poussé lors de l'échec au roi.",
    th: "หมากรุกเขมร (Ouk Chatrang) เป็นมรดกทางปัญญาพันปีแห่งอารยธรรมนครวัด ปรากฏภาพสลักบนกำแพงหินศิลาแลง ณ นครวัดและปราสาทบายนตั้งแต่คริสต์ศตวรรษที่ 12 คำว่า 'อุก' มาจากเสียงขานเมื่อรุกขุน",
    zh: "高棉象棋 (Ouk Chatrang) 是吴哥王朝流传千年的皇家智慧瑰宝，早在12世纪便栩栩如生地雕刻于吴哥窟与巴戎寺的沙岩浮雕之上。“Ouk”之名源自将军攻王时响彻宫廷的呼号。",
  },
  sec1_box1_title: {
    en: "Chaturanga Lineage",
    vi: "Khởi nguồn Chaturanga",
    km: "ប្រភពដើមចតុរង្គ",
    fr: "Lignée du Chaturanga",
    th: "ต้นกำเนิดจตุรงค์",
    zh: "四兵象棋源流",
  },
  sec1_box1_desc: {
    en: "Direct descendant of 6th-century Indian Chaturanga combined with Khmer military tactics.",
    vi: "Trực hệ từ cờ cổ Ấn Độ thế kỷ 6, hòa quyện với nghệ thuật quân sự Đế chế Khmer.",
    km: "មានប្រភពផ្ទាល់ពីអុកបុរាណឥណ្ឌាសតវត្សរ៍ទី ៦ រួមបញ្ចូលជាមួយយុទ្ធសាស្ត្រយោធាខ្មែរ។",
    fr: "Descendant direct du Chaturanga indien du VIe siècle combiné aux tactiques militaires khmères.",
    th: "สืบทอดโดยตรงจากจตุรงค์อินเดียโบราณศตวรรษที่ 6 ผสานยุทธวิธีทัพเขมรโบราณ",
    zh: "直接脉承6世纪古印度恰图兰卡，深度融合了高棉帝国的皇家军阵艺术。",
  },
  sec1_box2_title: {
    en: "Tonle Sap Fishery Culture",
    vi: "Văn hóa Biển Hồ Tonle Sap",
    km: "វប្បធម៌បឹងទន្លេសាប",
    fr: "Culture du Tonlé Sap",
    th: "วิถีชีวิตโตนเลสาบ",
    zh: "洞里萨湖水乡文化",
  },
  sec1_box2_desc: {
    en: "Pawns are represented as Fish (Trey), swimming upstream to promote into Trey Bork.",
    vi: "Quân Tốt mang hình tượng Cá (Trey), khi bơi đến thượng nguồn sẽ lật thành Cá Lớn (Trey Bork).",
    km: "កូនអុកតូចៗតំណាងដោយសត្វត្រី ដែលហែលបញ្ច្រាសទឹកឡើងទៅបកជាត្រីបក។",
    fr: "Les pions sont des Poissons (Trey), nageant vers l'amont pour devenir Trey Bork.",
    th: "เบี้ยเป็นตัวแทนของปลา (ตรี) ว่ายทวนน้ำขึ้นสู่ต้นน้ำเพื่อหงายเป็นเบี้ยหงาย",
    zh: "小兵以高棉生命之源“鱼”(Trey) 为化身，溯流而上抵达上游即升变为巨鱼大后。",
  },

  // Section 2
  sec2_text: {
    en: "The board consists of 64 uncheckered squares (8x8). A distinctive hallmark of Ouk Chatrang is that Trey pawns start on rank 3 (White) and rank 6 (Black) instead of ranks 2 & 7:",
    vi: "Bàn cờ gồm 64 ô vuông đơn sắc (8x8) không phân biệt màu ô. Điểm độc đáo nhất là dàn Tốt (Trey) nằm ở hàng 3 và hàng 6 thay vì hàng 2 và hàng 7 như cờ vua phương Tây:",
    km: "ក្តារអុកមាន ៦៤ ក្រឡាឯកសណ្ឋាន (៨x៨) គ្មានក្រឡាសខ្មៅឆ្លាស់គ្នាទេ។ ចំណុចពិសេសគឺត្រីឈរនៅជួរទី ៣ និងទី ៦៖",
    fr: "L'échiquier compte 64 cases unicolores (8x8). Particularité unique : les pions Trey débutent aux rangées 3 et 6 :",
    th: "กระกระดานประกอบด้วย 64 ช่องสีเดียว (8x8) จุดเด่นสำคัญคือเบี้ยตรีตั้งอยู่ที่แถวที่ 3 (ขาว) และแถวที่ 6 (ดำ):",
    zh: "棋盘由64个无明暗交替的单色方格 (8x8) 构成。高棉象棋最独特的特征是小兵 (Trey) 初始布设在第3横线与第6横线：",
  },
  sec2_backline_title: {
    en: "Backline (Ranks 1 & 8):",
    vi: "Tuyến Quân Sau (Hàng 1 & 8):",
    km: "ជួរទ័ពក្រោយ (ជួរទី ១ និង ៨)៖",
    fr: "Ligne Arrière (Rangées 1 & 8) :",
    th: "แถวหมากหลัก (แถว 1 และ 8):",
    zh: "后排主力阵容 (第1与第8横线)：",
  },
  sec2_backline_desc: {
    en: "White King (Ang) sits on e1 facing Black King on d8. White Queen (Neang) sits on d1 facing Black Queen on e8. Kings and Queens sit on opposite files.",
    vi: "Vua Trắng (Ang) ở ô e1 đối diện Vua Đen ở ô d8. Hậu Trắng (Neang) ở ô d1 đối diện Hậu Đen ở ô e8. Hai Vua luôn nằm chéo đối xứng nhau qua tâm.",
    km: "អង្គស (ស្តេច) នៅក្រឡា e1 ប្រឈមនឹងអង្គខ្មៅនៅ d8។ នាងសនៅ d1 ប្រឈមនាងខ្មៅនៅ e8។ ស្តេច និងនាងឈរទល់ទ្រូងគ្នា។",
    fr: "Le Roi Blanc (Ang) est en e1 face au Roi Noir en d8. La Reine Blanche (Neang) est en d1 face à la Reine Noire en e8.",
    th: "ขุนขาว (อัง) อยู่ช่อง e1 ตรงข้ามขุนดำที่ d8 เม็ดขาว (เนียง) อยู่ช่อง d1 ตรงข้ามเม็ดดำที่ e8",
    zh: "白王 (Ang) 位于e1格对准黑王d8格；白后 (Neang) 位于d1格对准黑后e8格。双方王后处于对角轴线布局。",
  },
  sec2_pawnline_title: {
    en: "Pawn Line (Ranks 3 & 6):",
    vi: "Tuyến Tiền Đồn (Hàng 3 & 6):",
    km: "ជួរត្រី (ជួរទី ៣ និង ៦)៖",
    fr: "Ligne des Pions (Rangées 3 & 6) :",
    th: "แถวเบี้ยตรี (แถว 3 และ 6):",
    zh: "前哨兵线 (第3与第6横线)：",
  },
  sec2_pawnline_desc: {
    en: "8 Trey pawns span across rank 3 (White) and rank 6 (Black).",
    vi: "8 quân Trey giăng ngang hàng 3 (Trắng) và hàng 6 (Đen).",
    km: "កូនត្រី ៨ ឈរតម្រៀបជួរទី ៣ (ស) និងជួរទី ៦ (ខ្មៅ)។",
    fr: "8 pions Trey alignés sur la rangée 3 (Blancs) et la rangée 6 (Noirs).",
    th: "เบี้ยตรี 8 ตัวเรียงเต็มแถวที่ 3 (ขาว) และแถวที่ 6 (ดำ)",
    zh: "8枚兵排布在白方第3横线与黑方第6横线，形成两军对垒的前沿接触线。",
  },

  // Section 3 Piece Descs
  piece_k_desc: {
    en: "Supreme Commander. Losing the King ends the match. Value: Infinite.",
    vi: "Vua / Thống soái tối cao. Mất Vua là thua trận. Giá trị: Vô giá.",
    km: "អង្គ / មេទ័ពកំពូល។ បាត់បង់អង្គគឺចាញ់ការប្រកួត។ តម្លៃ៖ ឥតកាត់ថ្លៃបាន។",
    fr: "Commandant Suprême. Perdre le Roi termine la partie. Valeur : Infinie.",
    th: "แม่ทัพสูงสุด เสียขุนคือแพ้เกม มูลค่า: ประเมินค่ามิได้",
    zh: "三军统帅。王陷落则全盘皆输。子力价值：无价。",
  },
  piece_q_desc: {
    en: "Queen / Palace Protector. Moves 1 diagonal square. Value: 3 points.",
    vi: "Hậu / Hộ vệ cung đình. Đi 1 ô chéo. Giá trị: 3 điểm.",
    km: "នាង / ឆ្មាំវាំង។ ដើរបញ្ឆិត ១ ក្រឡា។ តម្លៃ៖ ៣ ពិន្ទុ។",
    fr: "Reine / Protectrice du Palais. Se déplace d'une case en diagonale. Valeur : 3 points.",
    th: "เม็ด / องครักษ์วังหลวง เดินทแยง 1 ช่อง มูลค่า: 3 แต้ม",
    zh: "王后 / 宫廷护卫。向斜向走1格。子力价值：3分。",
  },
  piece_b_desc: {
    en: "War Elephant / Noble General. Moves 5 directions (4 diagonals + 1 forward). Value: 3 points.",
    vi: "Tượng chiến / Đại tướng quân. Đi 5 hướng (4 chéo + 1 tiến). Giá trị: 3 điểm.",
    km: "គោល (ដំរី) / មេទ័ពជាន់ខ្ពស់។ ដើរបាន ៥ ទិស (បញ្ឆិត ៤ + ត្រង់មុខ ១)។ តម្លៃ៖ ៣ ពិន្ទុ។",
    fr: "Éléphant de guerre / Général Noble. 5 directions (4 diagonales + 1 en avant). Valeur : 3 points.",
    th: "โคนคูล / แม่ทัพช้างศึก เดินได้ 5 ทิศทาง (ทแยง 4 + ตรงหน้า 1) มูลค่า: 3 แต้ม",
    zh: "战象 / 重装将军。可走5个方向（4个斜向+前直1格）。子力价值：3分。",
  },
  piece_n_desc: {
    en: "Cavalry Horse. L-shape jump over obstacles. Value: 4 points.",
    vi: "Kỵ binh Mã Ses. Nhảy chữ L vượt chướng ngại vật. Giá trị: 4 điểm.",
    km: "សេះ / កងទ័ពសេះ។ លោតរាងអក្សរ L រំលងឧបសគ្គ។ តម្លៃ៖ ៤ ពិន្ទុ។",
    fr: "Cavalier / Cheval de guerre. Saut en 'L' par-dessus les obstacles. Valeur : 4 points.",
    th: "ม้าศึกเซส เดินรูปตัว L กระโดดข้ามหมากตัวอื่นได้ มูลค่า: 4 แต้ม",
    zh: "骑兵烈马。走“日”字形并可自由跃过阻挡。子力价值：4分。",
  },
  piece_r_desc: {
    en: "Naval Warboat / Rook. Dominates orthogonal open files. Value: 8 points.",
    vi: "Thuyền chiến / Xe Tuuk. Khống chế toàn bộ cột dọc và hàng ngang. Giá trị: 8 điểm.",
    km: "ទូក / កងទ័ពជើងទឹក។ គ្រប់គ្រងជួរត្រង់ និងទទឹងទាំងអស់។ តម្លៃ៖ ៨ ពិន្ទុ។",
    fr: "Bateau de guerre / Tour. Domine les colonnes ouvertes orthogonales. Valeur : 8 points.",
    th: "เรือรบทูค คุมแนวตรงและแนวขวางทั้งกระดาน มูลค่า: 8 แต้ม",
    zh: "战船 / 车。统驭横竖开放线与全图纵深。子力价值：8分。",
  },
  piece_p_desc: {
    en: "Fish Pawn (1 pt). Promotes at opposing 6th rank to Trey Bork (3 pts).",
    vi: "Tốt Trey (1 điểm). Khi tiến lên hàng 6 đối phương, lật thành Trey Bork (3 điểm).",
    km: "កូនត្រី (១ ពិន្ទុ)។ ដល់ជួរទី ៦ របស់គូប្រកួត បកជាត្រីបក (៣ ពិន្ទុ)។",
    fr: "Pion Poisson (1 pt). Promu à la 6e rangée en Trey Bork (3 pts).",
    th: "เบี้ยปลาตรี (1 แต้ม) เมื่อเดินถึงแถว 6 หงายเป็นเบี้ยหงาย (3 แต้ม)",
    zh: "游鱼小兵 (1分)。推进至对方第6横线升变为后 (3分)。",
  },

  // Section 4 Movements
  mov_ang: {
    en: "1 step in any direction (8 neighboring squares).",
    vi: "1 ô mọi hướng (8 ô lân cận).",
    km: "១ ក្រឡាគ្រប់ទិស (៨ ក្រឡាជុំវិញ)។",
    fr: "1 case dans toutes les directions (8 cases).",
    th: "1 ช่องทุกทิศทาง (8 ช่องรอบตัว)",
    zh: "全方位相邻8个方格各走1步。",
  },
  mov_neang: {
    en: "1 step diagonally (4 corner squares).",
    vi: "1 ô chéo (4 góc).",
    km: "១ ក្រឡាបញ្ឆិត (៤ ទិស)។",
    fr: "1 case en diagonale (4 directions).",
    th: "1 ช่องแนวทแยง (4 ทิศ)",
    zh: "沿4个斜对角方向各走1步。",
  },
  mov_koul: {
    en: "1 step diagonally (4 directions) + 1 step straight forward.",
    vi: "1 ô chéo (4 hướng) + 1 ô tiến thẳng.",
    km: "១ ក្រឡាបញ្ឆិត (៤ ទិស) + ត្រង់ទៅមុខ ១ ក្រឡា។",
    fr: "1 case en diagonale (4 directions) + 1 case droit devant.",
    th: "1 ช่องแนวทแยง (4 ทิศ) + ตรงไปข้างหน้า 1 ช่อง",
    zh: "4个斜向各走1格，或向前直走1格（共5向）。",
  },
  mov_ses: {
    en: "L-shape jump (2+1), leaps over intervening pieces.",
    vi: "Chữ L (2+1), nhảy tự do qua các quân cản.",
    km: "រាងអក្សរ L (២+១) លោតរំលងកូនអុកដទៃ។",
    fr: "Saut en L (2+1), saute par-dessus les pièces.",
    th: "รูปตัว L (2+1) กระโดดข้ามหมากตัวอื่นได้",
    zh: "走“日”字形（2+1），可自由跃过阻挡。",
  },
  mov_tuuk: {
    en: "Orthogonally straight (rank & file) unlimited unobstructed distance.",
    vi: "Thẳng ngang/dọc không giới hạn ô thông thoáng.",
    km: "ត្រង់តាមបណ្តោយ និងទទឹងដោយគ្មានកំណត់ក្រឡា។",
    fr: "Lignes droites orthogonales sans limite d'obstacles.",
    th: "แนวตรงและแนวขวางไม่จำกัดช่องตราบใดที่ไม่มีหมากขวาง",
    zh: "横竖四条直线无限格滑行行驶。",
  },
  mov_trey: {
    en: "Trey: 1 step forward, captures 1 step diagonally. Trey Bork: moves/captures 1 step diagonally.",
    vi: "Trey: đi thẳng 1, ăn chéo 1. Trey Bork: đi/ăn chéo 1 ô 4 hướng.",
    km: "ត្រី៖ ដើរត្រង់ ១ ស៊ីបញ្ឆិត ១។ ត្រីបក៖ ដើរ/ស៊ីបញ្ឆិត ១ ក្រឡាទាំង ៤ ទិស។",
    fr: "Trey : 1 pas avant, capture en diagonale. Trey Bork : 1 case en diagonale 4 directions.",
    th: "เบี้ยตรี: เดินตรง 1 กินทแยง 1. เบี้ยหงาย: เดิน/กินทแยง 4 ทิศทางละ 1 ช่อง",
    zh: "兵：直走1格斜吃1格。升变兵：向4个斜向走或吃1格。",
  },

  // Section 5 Check & Mate
  sec5_check_title: {
    en: "Check (Ouk)",
    vi: "Chiếu tướng (Ouk)",
    km: "អុកស្តេច (Ouk)",
    fr: "Échec (Ouk)",
    th: "การรุก (Ouk)",
    zh: "将军 (Ouk)",
  },
  sec5_check_desc: {
    en: "Announced when an enemy piece directly attacks the King. The defender must resolve check immediately by fleeing, capturing the attacker, or blocking the ray.",
    vi: "Khi một quân cờ trực tiếp đe dọa ăn Vua. Người chơi phải hô 'Ouk!'. Bên bị chiếu bắt buộc phải: (1) Di chuyển Vua sang ô an toàn, (2) Ăn quân đang chiếu, hoặc (3) Dùng quân khác chắn đường chiếu (trừ khi bị Mã chiếu).",
    km: "នៅពេលកូនអុកគូប្រកួតគំរាមកំហែងដល់អង្គ។ ត្រូវស្រែកថា «អុក!»។ ភាគីការពារត្រូវរត់គេច ស៊ីកូនដែលអុក ឬដាក់កូនបាំងផ្លូវ។",
    fr: "Annoncé lorsqu'une pièce attaque directement le Roi. Le défenseur doit parer l'échec en fuyant, en capturant l'attaquant ou en interposant une pièce.",
    th: "เกิดขึ้นเมื่อหมากฝ่ายตรงข้ามเข้าโจมตีขุน ต้องขานว่า 'อุก!' ฝ่ายรับต้องหนีขุน กินตัวรุก หรือนำหมากอื่นมาบัง",
    zh: "当敌方棋子直接攻击王时必须高呼“Ouk!”。被将军方必须立即应将：移王避险、吃掉攻王之子或垫子阻截（马将军不可阻截）。",
  },
  sec5_mate_title: {
    en: "Checkmate (Ouk Ngueb)",
    vi: "Chiếu bí (Ouk Ngueb)",
    km: "អុកងាប់ (Ouk Ngueb)",
    fr: "Échec et Mat (Ouk Ngueb)",
    th: "การรุกจน (Ouk Ngueb)",
    zh: "杀局 / 将死 (Ouk Ngueb)",
  },
  sec5_mate_desc: {
    en: "When the King is in check and has no legal escape moves left. The match ends immediately with a decisive victory for the attacker.",
    vi: "Khi Vua đang bị chiếu mà không còn bất kỳ nước đi hợp lệ nào để thoát. Ván cờ lập tức kết thúc với chiến thắng thuộc về bên tấn công!",
    km: "នៅពេលអង្គកំពុងជាប់អុក ហើយគ្មានច្រកណាអាចរត់គេចបានទៀតឡើយ។ ការប្រកួតបញ្ចប់ភ្លាមៗដោយជ័យជម្នះ។",
    fr: "Lorsque le Roi est en échec et ne dispose d'aucun coup légal de fuite. La partie se termine immédiatement par la victoire.",
    th: "เมื่อขุนถูกรุกและไม่มีตาเดินที่ถูกต้องเพื่อหลบหนีได้อีก จบเกมด้วยชัยชนะของฝ่ายโจมตีทันที",
    zh: "当王受将军且无任何合法应将着法时即为杀局。进攻方获得干脆利落的绝杀胜利！",
  },

  // Section 6 Openings
  sec6_open1_title: {
    en: "1. Pawn Chain (Xích Tốt)",
    vi: "1. Xích Tốt Liên Hoàn (Pawn Chain)",
    km: "១. ខ្សែត្រីតភ្ជាប់ (Pawn Chain)",
    fr: "1. Chaîne de Pions Liés",
    th: "1. การผูกเบี้ยตรี (Pawn Chain)",
    zh: "1. 连环兵阵 (Pawn Chain)",
  },
  sec6_open1_desc: {
    en: "Build connected diagonal pawn chains (c3-d4-e4) to control center squares and anchor outposts.",
    vi: "Dựng các cặp Tốt chéo nhau (c3-d4-e4) để bảo vệ nhau, chiếm lĩnh trung tâm và kiểm soát các ô tiền đồn quan trọng.",
    km: "រៀបចំកូនត្រីបញ្ឆិតតភ្ជាប់គ្នាដើម្បីការពារគ្នា គ្រប់គ្រងកណ្តាលក្តារ និងបង្កើតមូលដ្ឋានទ័ព។",
    fr: "Construire des chaînes de pions diagonales connectées (c3-d4-e4) pour dominer le centre.",
    th: "ผูกเบี้ยทะแยงเกื้อหนุนกัน (c3-d4-e4) เพื่อคุมศูนย์กลางและสร้างฐานที่มั่น",
    zh: "构筑斜向相互生根的连环兵阵（如c3-d4-e4），牢固控制中腹要道与战略支撑点。",
  },
  sec6_open2_title: {
    en: "2. Ses Cavalry Outposts",
    vi: "2. Xuất Mã Chiếm Điểm Cao (Ses Outposts)",
    km: "២. បញ្ចេញទ័ពសេះដណ្តើមទីតាំង",
    fr: "2. Avant-postes de Cavalerie Ses",
    th: "2. การพัฒนาขุนพลม้าสู่ศูนย์กลาง",
    zh: "2. 飞马抢占中腹高地 (Ses Outposts)",
  },
  sec6_open2_desc: {
    en: "Deploy horses to central squares behind the pawn chain to prepare attacking leaps.",
    vi: "Đưa Mã lên các ô trung tâm đằng sau xích tốt (c3, f3 / c6, f6) để sẵn sàng đột phá vào hàng ngũ đối phương.",
    km: "បញ្ជូនសេះឡើងទៅក្រឡាកណ្តាលពីក្រោយខ្សែត្រី ដើម្បីត្រៀមលោតវាយប្រហារ។",
    fr: "Déployer les chevaux sur les cases centrales derrière la chaîne de pions.",
    th: "นำม้าขึ้นคุมจุดยุทธศาสตร์หลังแนวเบี้ยเพื่อเตรียมกระโดดโจมตี",
    zh: "将战马部署于兵阵庇护下的中央要点（c3, f3 / c6, f6），伺机破阵突袭。",
  },
  sec6_open3_title: {
    en: "3. Palace Fortification",
    vi: "3. Củng Cố Cung Điện (Palace Fortification)",
    km: "៣. ពង្រឹងបន្ទាយការពារអង្គ",
    fr: "3. Fortification du Palais Royal",
    th: "3. การวางแนวคุ้มกันพระราชวัง",
    zh: "3. 巩固王宫要塞 (Palace Fortification)",
  },
  sec6_open3_desc: {
    en: "Coordinate Koul and Neang around King Ang to build an impenetrable fortress before opening files for Tuuk.",
    vi: "Di chuyển Tượng Koul và Hậu Neang bao bọc lấy Vua Ang, tạo thành thế phòng thủ vững chắc trước khi mở cột cho Thuyền Tuuk.",
    km: "រៀបចំគោល និងនាងការពារអង្គឱ្យរឹងមាំ មុននឹងបើកផ្លូវឱ្យទូកធ្វើសកម្មភាព។",
    fr: "Coordonner le Koul et la Neang autour du Roi Ang avant d'ouvrir les colonnes pour le Tuuk.",
    th: "ประสานโคนคูลและเม็ดเนียงรอบขุนอังเป็นปราการหนาแน่น ก่อนเปิดช่องให้เรือทูค",
    zh: "调动相 (Koul) 与后 (Neang) 严密拱卫王 (Ang)，筑就铁壁要塞后方行开启车路。",
  },

  // Section 7 Tactics
  sec7_tac1_title: {
    en: "The Cavalry Fork (Đòn Chĩa Đôi Của Mã)",
    vi: "Đòn Chĩa Đôi Của Mã (The Cavalry Fork)",
    km: "ក្បាច់សេះចាក់ពីរ (The Cavalry Fork)",
    fr: "La Fourchette de Cavalerie du Ses",
    th: "ตาม้าซ้อนสองทาง (The Cavalry Fork)",
    zh: "八面金锁双抽马叉 (Cavalry Fork)",
  },
  sec7_tac1_desc: {
    en: "The knight leaps into a key square attacking two high-value targets (e.g. King and Boat) simultaneously.",
    vi: "Mã Ses nhảy vào ô then chốt, đồng thời đe dọa 2 mục tiêu giá trị cao (như Vua và Xe Tuuk). Buộc đối phương phải mất quân nặng.",
    km: "សេះលោតចូលក្រឡាសំខាន់ គំរាមកំហែងគោលដៅធំៗពីរក្នុងពេលតែមួយ (ដូចជាស្តេច និងទូក)។",
    fr: "Le cavalier saute sur une case clé pour menacer deux pièces majeures simultanément.",
    th: "ม้ากระโดดเข้าตาสำคัญ โจมตีเป้าหมายมูลค่าสูงสองตัวพร้อมกัน (เช่น ขุนและเรือ)",
    zh: "战马突入枢纽格，同时将军并捉车，令敌方顾此失彼必失重子。",
  },
  sec7_tac2_title: {
    en: "Double Boat Battery (Song Thuyền Cột Mở)",
    vi: "Song Thuyền Cột Mở (Double Boat Battery)",
    km: "ទូកភ្លោះគ្រប់គ្រងជួរ (Double Boat Battery)",
    fr: "Batterie de Doubles Bateaux Tuuk",
    th: "เรือคู่คุมแนวเปิด (Double Boat Battery)",
    zh: "双船重炮重叠贯通 (Double Boat Battery)",
  },
  sec7_tac2_desc: {
    en: "Stacking two Tuuk warboats on an open file to penetrate the opponent's backline.",
    vi: "Ghép 2 Thuyền Tuuk trên cùng một cột dọc đã thông Tốt, quét sạch tuyến phòng thủ của đối phương và dồn Vua vào góc chết.",
    km: "ផ្គុំទូកពីរនៅលើជួរតែមួយដែលបើកផ្លូវ ដើម្បីទម្លុះបន្ទាយការពាររបស់គូប្រកួត។",
    fr: "Empiler deux bateaux Tuuk sur une colonne ouverte pour pénétrer la défense ennemie.",
    th: "ซ้อนเรือรบสองลำในแถวเปิดเพื่อเจาะทะลวงแนวป้องกันและบดขยี้ฝ่ายตรงข้าม",
    zh: "将两艘战船配置在同一条通畅纵线上，形成雷霆万钧之势荡平防线。",
  },

  // Section 8 Folk Rules
  sec8_header: {
    en: "Traditional Folk Privileges:",
    vi: "Đặc Quyền Khai Cuộc Dân Gian:",
    km: "ឯកសិទ្ធិច្បាប់បុរាណប្រពៃណី៖",
    fr: "Privilèges traditionnels folkloriques :",
    th: "สิทธิพิเศษในกติกาพื้นบ้านดั้งเดิม:",
    zh: "高棉传统民间对局特权：",
  },
  sec8_rule1: {
    en: "King (Ang) on move 1 may leap like a Knight if it has not been checked.",
    vi: "Vua (Ang) ở nước đi đầu tiên có thể nhảy như Mã (hình chữ L) sang 1 ô trống nếu Vua chưa bị chiếu.",
    km: "អង្គ (ស្តេច) ក្នុងដំណើរដើរដំបូងអាចលោតដូចសេះបាន ប្រសិនបើមិនទាន់ត្រូវជាប់អុក។",
    fr: "Le Roi (Ang) au 1er coup peut sauter comme un cavalier s'il n'a pas été mis en échec.",
    th: "ขุน (อัง) ในตาเดินแรกสามารถกระโดดแบบม้าได้หากยังไม่เคยถูกรุก",
    zh: "王 (Ang) 在尚未被将军的前提下，第一步可行使特权如马一般跳跃入阵。",
  },
  sec8_rule2: {
    en: "Queen (Neang) on move 1 may jump 2 squares straight forward if unobstructed.",
    vi: "Hậu (Neang) ở nước đi đầu tiên có thể nhảy 2 ô thẳng về phía trước nếu đường đi thông thoáng.",
    km: "នាងក្នុងដំណើរដើរដំបូងអាចលោតត្រង់ទៅមុខ ២ ក្រឡាបាន ប្រសិនបើគ្មានកូនរារាំង។",
    fr: "La Reine (Neang) au 1er coup peut sauter de 2 cases tout droit si la voie est libre.",
    th: "เม็ด (เนียง) ในตาเดินแรกสามารถกระโดดตรงไปข้างหน้าได้ 2 ช่องหากไม่มีหมากขวาง",
    zh: "后 (Neang) 在首步可直向向前跳跃2格（前提是前进路径无障碍）。",
  },
  sec8_rule3: {
    en: "No chess clock required; relaxed, conversational, and cultural atmosphere.",
    vi: "Không bắt buộc dùng đồng hồ bấm giờ; người chơi giao lưu tự do, thân thiện.",
    km: "មិនតម្រូវឱ្យប្រើនាឡិកាកំណត់ពេលឡើយ រីករាយនឹងបរិយាកាសមិត្តភាព។",
    fr: "Aucune pendule requise ; ambiance conviviale, culturelle et détendue.",
    th: "ไม่บังคับใช้นาฬิกาจับเวลา บรรยากาศเป็นกันเองและผ่อนคลาย",
    zh: "无需严苛棋钟限时，注重棋道修养、切磋交流与文化传承。",
  },

  // Section 9 International Rules
  sec9_header: {
    en: "International Tournament Standards (SEA Games):",
    vi: "Quy Chuẩn Thi Đấu Thể Thao Quốc Tế (SEA Games):",
    km: "បទដ្ឋានប្រកួតកីឡាអន្តរជាតិស៊ីហ្គេម (SEA Games)៖",
    fr: "Normes de tournoi internationales (Jeux d'Asie du Sud-Est) :",
    th: "มาตรฐานการแข่งขันระดับสากลและกีฬาซีเกมส์ (SEA Games):",
    zh: "东南亚运动会 (SEA Games) 国际锦标赛竞技标准：",
  },
  sec9_rule1: {
    en: "Opening leaps for King and Queen are strictly forbidden.",
    vi: "Bãi bỏ toàn bộ đặc quyền nhảy nước đầu của Vua và Hậu (chỉ đi đúng nước chuẩn).",
    km: "ហាមឃាត់ដាច់ខាតការលោតបើកឆាករបស់អង្គ និងនាង។",
    fr: "Les sauts initiaux du Roi et de la Reine sont strictement abolis.",
    th: "ยกเลิกตากระโดดเปิดเกมของขุนและเม็ดทั้งหมด (เดินตามกติกามาตรฐาน)",
    zh: "严禁王与后的首步跳跃特权，一切按标准单格走法执行。",
  },
  sec9_rule2: {
    en: "Strict Touch-Move rule: Touching a piece with legal moves requires moving it.",
    vi: "Luật Chạm Quân (Touch-Move): Đã chạm vào quân nào có nước đi hợp lệ thì bắt buộc phải đi quân đó.",
    km: "ច្បាប់ប៉ះកូនណាត្រូវដើរកូននោះ (Touch-Move) ប្រសិនបើមានក្រឡាដើរស្របច្បាប់។",
    fr: "Règle stricte 'Pièce touchée, pièce jouée' (Touch-Move).",
    th: "กฎแตะต้องหมาก (Touch-Move) แตะหมากตัวใดที่มีตาเดินต้องเดินตัวนั้น",
    zh: "严格执行“摸子动子”(Touch-Move) 竞技准则，触碰合法棋子必须走动。",
  },
  sec9_rule3: {
    en: "Official chess clock: Standard (60m) or Blitz (5m).",
    vi: "Đồng hồ thi đấu: 60 phút tiêu chuẩn (Standard) hoặc 5 phút chớp (Blitz).",
    km: "នាឡិកាប្រកួតផ្លូវការ៖ ស្តង់ដារ ៦០ នាទី ឬ រហ័ស ៥ នាទី។",
    fr: "Horloge officielle : Standard (60 min) ou Blitz (5 min).",
    th: "นาฬิกาจับเวลามาตรฐาน: 60 นาที (Standard) หรือ 5 นาที (Blitz)",
    zh: "官方规范计时：标准赛每方60分钟，快棋赛每方5分钟包干。",
  },
  sec9_rule4: {
    en: "Tournament scoring: Win = 1.0, Draw = 0.5, Loss = 0.0.",
    vi: "Điểm số thi đấu: Thắng = 1.0 điểm, Hòa = 0.5 điểm, Thua = 0.0 điểm.",
    km: "ពិន្ទុប្រកួត៖ ឈ្នះ = ១.០ ពិន្ទុ, ស្មើ = ០.៥ ពិន្ទុ, ចាញ់ = ០.០ ពិន្ទុ។",
    fr: "Score de tournoi : Victoire = 1.0, Nulle = 0.5, Défaite = 0.0.",
    th: "ระบบคะแนนแข่งขัน: ชนะ = 1.0, เสมอ = 0.5, แพ้ = 0.0",
    zh: "国际巡回积分制：胜局 = 1.0分，和局 = 0.5分，负局 = 0.0分。",
  },

  // Section 10 Endgame Counting (Mij / Viel)
  sec10_intro: {
    en: "The Mij / Viel endgame counting system is a unique masterpiece of Ouk Chatrang, allowing a defending player to claim a draw if the attacker cannot deliver checkmate within the move threshold:",
    vi: "Hệ thống đếm tàn cuộc (Mij / Viel) là nét đặc sắc độc nhất vô nhị của Cờ Ốc, cho phép bên yếu thế thủ hòa nếu bên tấn công không thể chiếu bí trong số nước quy định:",
    km: "ប្រព័ន្ធរាប់វាល (មីជ / វាល) គឺជាចំណុចពិសេសអស្ចារ្យផ្តាច់មុខនៃអុកចត្រង្គ ដែលអនុញ្ញាតឱ្យភាគីការពារទាមទារស្មើ ប្រសិនបើភាគីវាយលុកមិនអាចអុកងាប់ក្នុងចំនួនទឹកកំណត់៖",
    fr: "Le système de comptage de fin de partie Mij / Viel permet au défenseur d'obtenir la nulle si l'attaquant ne mate pas dans la limite impartie :",
    th: "ระบบการนับศักดิ์ปลายกระดาน (มิจ/เวียล) เป็นเอกลักษณ์พิเศษที่เปิดโอกาสให้ฝ่ายรับสามารถขอเสมอได้หากฝ่ายรุกไม่สามารถรุกจนในจำนวนตาที่กำหนด:",
    zh: "高棉象棋独步天下的残局数步（Mij / Viel）规则，赋予劣势守方在攻方无法于限定步数内绝杀时判和的权利：",
  },
  sec10_board_count_title: {
    en: "1. Board Counting (Viel K'dar) — 64 Moves Limit",
    vi: "1. Đếm Bàn Cờ (Viel K'dar) — Giới hạn 64 Nước",
    km: "១. ការរាប់ក្តារ (វាលក្តារ) — កំណត់ត្រឹម ៦៤ ទឹក",
    fr: "1. Comptage de l'Échiquier (Viel K'dar) — Limite de 64 Coups",
    th: "1. การนับกระดาน (เวียลกระดาน) — จำกัด 64 ตาเดิน",
    zh: "1. 全盘棋格数步 (Viel K'dar) — 上限64步",
  },
  sec10_board_count_desc: {
    en: "Triggered when all Trey pawns are either captured or promoted to Trey Bork. Defending side counts up to 64 moves.",
    vi: "Kích hoạt khi không còn quân Tốt Trey nào trên bàn chưa lật (toàn bộ Tốt đã bị ăn hoặc đã phong cấp thành Trey Bork). Bên phòng thủ được đếm tối đa 64 nước để cầm hòa.",
    km: "ចាប់ផ្តើមនៅពេលដែលគ្មានកូនត្រីដើមនៅលើក្តារទៀតឡើយ (ត្រូវស៊ីអស់ ឬបកជាត្រីបកទាំងអស់)។ ភាគីការពាររាប់ដល់ ៦៤ ទឹកដើម្បីស្មើ។",
    fr: "Activé quand tous les pions Trey sont capturés ou promus en Trey Bork. Le défenseur compte jusqu'à 64 coups pour faire nulle.",
    th: "เริ่มต้นเมื่อไม่มีเบี้ยตรีธรรมดาบนกระดาน (ถูกกินหมดหรือหงายเป็นเบี้ยหงายทั้งหมด) ฝ่ายรับนับได้สูงสุด 64 ตาเพื่อเสมอ",
    zh: "当局面上所有原始小兵均已被吃或均已升变为后时启动。守方可启动64步棋格倒计时以谋和。",
  },
  sec10_piece_count_title: {
    en: "2. Piece Counting (Viel L'koun) — Attack Strength Limit",
    vi: "2. Đếm Đại Tử / Lực Lượng (Viel L'koun) — Độc Nhất Vô Nhị",
    km: "២. ការរាប់កូនអុក (វាលកូន) — កំណត់តាមកម្លាំងទ័ពវាយប្រហារ",
    fr: "2. Comptage par Pièces (Viel L'koun) — Limite de Force Offensive",
    th: "2. การนับศักดิ์หมาก (เวียลศักดิ์) — จำกัดตามหมากโจมตีสูงสุด",
    zh: "2. 战子子力数步 (Viel L'koun) — 依攻方最强子力定步",
  },
  sec10_piece_count_desc: {
    en: "Triggered when the defending player has only a lone King. Step limit is set by the attacker's strongest surviving piece:",
    vi: "Kích hoạt khi một bên chỉ còn lại duy nhất một Vua Đơn Độc (Sdaach/Ang). Giới hạn số nước chiếu bí được xác định theo quân mạnh nhất của bên tấn công:",
    km: "ចាប់ផ្តើមនៅពេលដែលភាគីម្ខាងសល់តែអង្គទោលមួយគត់។ កម្រិតទឹកអុកងាប់ត្រូវបានកំណត់ដោយកូនអុកខ្លាំងបំផុតរបស់ភាគីវាយលុក៖",
    fr: "Déclenché quand le défenseur n'a plus qu'un Roi isolé. La limite est déterminée par la pièce adverse la plus forte :",
    th: "เริ่มต้นเมื่อฝ่ายรับเหลือเพียงขุนเดี่ยวตัวเดียว จำนวนตาเดินจะถูกกำหนดโดยหมากที่แข็งแกร่งที่สุดของฝ่ายรุก:",
    zh: "当防守方仅剩单王孤军奋战时启动。杀王步数上限由攻方幸存的最强战子种类严格判定：",
  },
  moves_unit: {
    en: "moves",
    vi: "nước",
    km: "ទឹក",
    fr: "coups",
    th: "ตา",
    zh: "步",
  },
  c_2boats: {
    en: "2 Boats (Tuuk):",
    vi: "2 Thuyền (Tuuk):",
    km: "ទូក ២ (Tuuk):",
    fr: "2 Bateaux (Tuuk) :",
    th: "เรือ 2 ลำ (Tuuk):",
    zh: "双车/双船 (Tuuk)：",
  },
  c_1boat: {
    en: "1 Boat (Tuuk):",
    vi: "1 Thuyền (Tuuk):",
    km: "ទូក ១ (Tuuk):",
    fr: "1 Bateau (Tuuk) :",
    th: "เรือ 1 ลำ (Tuuk):",
    zh: "单车/单船 (Tuuk)：",
  },
  c_2elephants: {
    en: "2 Elephants (Koul):",
    vi: "2 Tượng (Koul):",
    km: "គោល ២ (Koul):",
    fr: "2 Éléphants (Koul) :",
    th: "โคน 2 ตัว (Koul):",
    zh: "双相/双象 (Koul)：",
  },
  c_2horses: {
    en: "2 Horses (Ses):",
    vi: "2 Mã (Ses):",
    km: "សេះ ២ (Ses):",
    fr: "2 Chevaux (Ses) :",
    th: "ม้า 2 ตัว (Ses):",
    zh: "双马 (Ses)：",
  },
  c_1elephant: {
    en: "1 Elephant (Koul):",
    vi: "1 Tượng (Koul):",
    km: "គោល ១ (Koul):",
    fr: "1 Éléphant (Koul) :",
    th: "โคน 1 ตัว (Koul):",
    zh: "单相/单象 (Koul)：",
  },
  c_1horse_or_other: {
    en: "1 Horse / Queen / Trey Bork:",
    vi: "1 Mã / Hậu / Tốt lật:",
    km: "សេះ ១ / នាង / ត្រីបក:",
    fr: "1 Cheval / Reine / Trey Bork :",
    th: "ม้า 1 ตัว / เม็ด / เบี้ยหงาย:",
    zh: "单马 / 后 / 升变兵：",
  },
};
