/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as PlayRouteImport } from './routes/play'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TacticsRouteImport } from './routes/tactics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsRoute = TacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/online': typeof OnlineRoute
  '/play': typeof PlayRoute
  '/settings': typeof SettingsRoute
  '/tactics': typeof TacticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/online': typeof OnlineRoute
  '/play': typeof PlayRoute
  '/settings': typeof SettingsRoute
  '/tactics': typeof TacticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/online': typeof OnlineRoute
  '/play': typeof PlayRoute
  '/settings': typeof SettingsRoute
  '/tactics': typeof TacticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/home'
    | '/leaderboard'
    | '/online'
    | '/play'
    | '/settings'
    | '/tactics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/home'
    | '/leaderboard'
    | '/online'
    | '/play'
    | '/settings'
    | '/tactics'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/home'
    | '/leaderboard'
    | '/online'
    | '/play'
    | '/settings'
    | '/tactics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OnlineRoute: typeof OnlineRoute
  PlayRoute: typeof PlayRoute
  SettingsRoute: typeof SettingsRoute
  TacticsRoute: typeof TacticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics': {
      id: '/tactics'
      path: '/tactics'
      fullPath: '/tactics'
      preLoaderRoute: typeof TacticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LeaderboardRoute: LeaderboardRoute,
  OnlineRoute: OnlineRoute,
  PlayRoute: PlayRoute,
  SettingsRoute: SettingsRoute,
  TacticsRoute: TacticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
